# Licensed under the Apache License, Version 2.0.

[package]
name = "tesseract-protocol-substrate"
version = "0.1.0"
authors = ["Tesseract Systems, Inc. <contact@tesseract.one>"]
description = "Tesseract protocol for Substrate based networks"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
client = ["tesseract/client"]
service = ["tesseract/service"]
# default = ["client", "service"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-trait = { version = "0.1"}
tesseract = { path = "../../tesseract" }

[dev-dependencies]
subxt = "0.23.0"
futures = { version = "0.3", features = ["thread-pool"] }
sp-core = "6.0.0"
scale-value = "0.5.0"
jsonrpsee-core = "0.15.1"
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
rand = "0.8.5"

[[test]]
name = "subxt_local_test"
path = "tests/subxt_local_test.rs"
required-features = ["client", "service"]