# Licensed under the Apache License, Version 2.0.

[package]
name = "tesseract-protocol-substrate"
version = "0.1.0"
authors = ["Tesseract Systems, Inc. <contact@tesseract.one>"]
description = "Tesseract protocol for Substrate based networks"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
client = ["tesseract/client"]
service = ["tesseract/service"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-trait = { version = "0.1"}
tesseract = { path = "../../tesseract" }
